<?php
/**
 * Admin Portal - 1-Click Database Backup & System Snapshot
 * Generates and downloads a complete SQL snapshot of all database tables and rows
 */

require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../includes/auth_check.php';

require_login();
require_admin();
$adminUser = current_user();
$db = get_db();

// Handle SQL Dump Download
if (isset($_GET['action']) && $_GET['action'] === 'download_sql') {
    $filename = 'craftbrew_backup_' . date('Y-m-d_His') . '.sql';

    header('Content-Type: application/sql; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Pragma: no-cache');
    header('Expires: 0');

    $out = fopen('php://output', 'w');

    fwrite($out, "-- ======================================================\n");
    fwrite($out, "-- CraftBrew Platform Database Backup Snapshot\n");
    fwrite($out, "-- Version: " . APP_VERSION . "\n");
    fwrite($out, "-- Timestamp: " . date('Y-m-d H:i:s') . "\n");
    fwrite($out, "-- Generated by: " . $adminUser['username'] . " (IP: " . get_client_ip() . ")\n");
    fwrite($out, "-- ======================================================\n\n");
    fwrite($out, "SET FOREIGN_KEY_CHECKS=0;\n");
    fwrite($out, "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n");
    fwrite($out, "SET time_zone = \"+00:00\";\n\n");

    // Fetch all tables
    $tables = $db->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

    foreach ($tables as $table) {
        fwrite($out, "-- ------------------------------------------------------\n");
        fwrite($out, "-- Table structure for table `{$table}`\n");
        fwrite($out, "-- ------------------------------------------------------\n");
        fwrite($out, "DROP TABLE IF EXISTS `{$table}`;\n");

        $createStmt = $db->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_ASSOC);
        fwrite($out, $createStmt['Create Table'] . ";\n\n");

        fwrite($out, "-- Dumping data for table `{$table}`\n");
        $rows = $db->query("SELECT * FROM `{$table}`")->fetchAll(PDO::FETCH_ASSOC);

        if (!empty($rows)) {
            foreach ($rows as $row) {
                $cols = array_map(function($c) { return "`" . str_replace("`", "``", $c) . "`"; }, array_keys($row));
                $vals = array_map(function($v) use ($db) {
                    if (is_null($v)) return "NULL";
                    return $db->quote($v);
                }, array_values($row));

                fwrite($out, "INSERT INTO `{$table}` (" . implode(", ", $cols) . ") VALUES (" . implode(", ", $vals) . ");\n");
            }
            fwrite($out, "\n");
        }
    }

    fwrite($out, "SET FOREIGN_KEY_CHECKS=1;\n");
    fwrite($out, "-- Backup completed successfully.\n");
    fclose($out);

    log_admin_action('database_backup', "Downloaded full SQL database backup snapshot ({$filename})");
    exit;
}

// Fetch database telemetry
$tablesList = $db->query("SHOW TABLE STATUS")->fetchAll(PDO::FETCH_ASSOC);
$totalRows = 0;
$totalSizeBytes = 0;

foreach ($tablesList as $t) {
    $totalRows += (int)($t['Rows'] ?? 0);
    $totalSizeBytes += (int)($t['Data_length'] ?? 0) + (int)($t['Index_length'] ?? 0);
}

$totalSizeFormatted = round($totalSizeBytes / (1024 * 1024), 2) . ' MB';

$csrfToken = generate_csrf_token();
$pageTitle = "Database Backup - Admin Portal";
$activePage = 'admin';
$adminSubPage = 'backup';
require_once __DIR__ . '/../includes/header.php';
?>

<?php require_once __DIR__ . '/nav.php'; ?>

<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem; flex-wrap: wrap; gap: 1rem;">
    <div>
        <h2>💾 Database Backup &amp; System Snapshot</h2>
        <p style="color: var(--text-muted);">Generate and download instant, portable SQL snapshots of your entire brewing dataset.</p>
    </div>
    <a href="backup.php?action=download_sql" class="btn btn-primary" style="display: flex; align-items: center; gap: 0.5rem;">
        📥 Download Full Database SQL Backup (.sql)
    </a>
</div>

<!-- Backup Telemetry Cards -->
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; margin-bottom: 1.75rem;">
    <div class="card stat-card">
        <div class="stat-val"><?= count($tablesList) ?></div>
        <div class="stat-lbl">📦 Database Tables</div>
    </div>
    <div class="card stat-card">
        <div class="stat-val"><?= number_format($totalRows) ?></div>
        <div class="stat-lbl">📊 Total Records / Rows</div>
    </div>
    <div class="card stat-card">
        <div class="stat-val"><?= $totalSizeFormatted ?></div>
        <div class="stat-lbl">💾 Total Database Size</div>
    </div>
</div>

<!-- Tables Breakdown Table -->
<div class="card" style="padding: 0; overflow-x: auto;">
    <div style="padding: 1.25rem 1.25rem 0.5rem 1.25rem;">
        <h3 class="card-title">📋 Database Schema &amp; Table Inventory</h3>
    </div>
    <table class="data-table" style="font-size: 0.9rem;">
        <thead>
            <tr>
                <th>Table Name</th>
                <th>Estimated Rows</th>
                <th>Data Size</th>
                <th>Engine / Collation</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tablesList as $tbl): ?>
                <tr>
                    <td><code><?= e($tbl['Name']) ?></code></td>
                    <td><?= number_format((int)$tbl['Rows']) ?></td>
                    <td><?= round(((int)$tbl['Data_length'] + (int)$tbl['Index_length']) / 1024, 1) ?> KB</td>
                    <td><?= e($tbl['Engine']) ?> (<?= e($tbl['Collation']) ?>)</td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
